//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Summerslam_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pick
    {
        public int PID { get; set; }
        public int HID { get; set; }
        public string Universal { get; set; }
        public string Heavyweight { get; set; }
        public string RWomen { get; set; }
        public string SDWomen { get; set; }
        public string RawTag { get; set; }
        public string SDTag { get; set; }
        public string IC { get; set; }
        public string US { get; set; }
        public string CW { get; set; }
        public string DBMiz { get; set; }
        public string MITB { get; set; }
        public string BalCorbin { get; set; }
        public string AlmasRusev { get; set; }
        public string LashElias { get; set; }
        public string BossSquad { get; set; }
    
        public virtual Human Human { get; set; }
    }
}
